feat!: new project init

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -1,5 +1,9 @@
 name: Nuxt CI
 
+permissions:
+  contents: write
+  pull-requests: write
+
 on:
   push:
     branches:
@@ -7,33 +11,61 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-24.04
+    if: >
+      !(
+        contains(github.event.head_commit.message, 'ci(release):') ||
+        contains(github.event.head_commit.message, '[skip ci]') ||
+        startsWith(github.event.head_commit.message, 'Merge pull request') ||
+        startsWith(github.event.head_commit.message, 'Merge branch')
+      )
+    runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repo
+      - name: 📥 Checkout Repo
         uses: actions/checkout@v4
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
         with:
-          node-version: '20.x'
-          cache: 'npm'
+          fetch-depth: 0
 
-      - name: Install Dependencies
-        run: npm ci
+      - name: 🛠️ Setup Bun
+        uses: oven-sh/setup-bun@v2
+        with:
+          bun-version: latest
 
-      # - name: Run Tests
-      # run: npm test
+      - name: 📦 Install Dependencies
+        run: bun install --frozen-lockfile
 
-      # - name: Lint Code
-      #   run: npm run link:fix
+      - name: ⚙️ Build Artifact
+        run: bun run build
 
-      # - name: Format Code
-      #   run: npm run format
+      # - name: ✅ Test Code
+      #   run: bun run test
 
-      - name: Bulid Artifacts
-        run: npm run build
+      - name: 🧹 Lint Code
+        run: bun run lint || echo "Linting failed, but continuing"
 
-      - name: Create Release Pull Request
-        uses: changesets/action@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: 🧼 Format Code
+        run: bun run format
+
+      - name: 🤖 AutoFix Code
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: 'chore: apply code fixes [skip ci]'
+
+      - name: 🏷️ Bump Version
+        id: bump_version
+        run: |
+          rm -f CHANGELOG.md
+          bunx changelogen@latest --bump
+          CHLOG=$(cat CHANGELOG.md)
+          echo -e "CHANGELOG_CONTENT<<EOF\n${CHLOG}\nEOF" >> $GITHUB_ENV
+          git reset --hard
+          bunx changelogen@latest --bump
+
+      - name: 🔀 Create or Update Pull Request
+        uses: peter-evans/create-pull-request@v7
+        with:
+          commit-message: 'ci(release): update version'
+          title: 'ci(release): update version'
+          body: ${{ env.CHANGELOG_CONTENT }}
+          branch: 'release/update-version'
+          base: 'develop'
+          delete-branch: true
